version: '3.8'

services:
  db:
    image: postgres:13-bullseye
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${SECUREAUTH_DB_USERNAME}
      POSTGRES_PASSWORD: ${SECUREAUTH_DB_PASSWORD}
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
      - bundle_data:/usr/local/bundle
    ports:
      - "3000:3000"
    environment:
      DB_HOST: ${SECUREAUTH_DB_HOST}
      DB_USERNAME: ${SECUREAUTH_DB_USERNAME}
      DB_PASSWORD: ${SECUREAUTH_DB_PASSWORD}
      DEV_DB_NAME: ${SECUREAUTH_DEV_DB_NAME}
      TEST_DB_NAME: ${SECUREAUTH_TEST_DB_NAME}
    depends_on:
      - db
    command: bash -c "bundle install && bundle exec rails s -b 0.0.0.0"
  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - "1080:1080"  # Web interface
      - "1025:1025"  # SMTP server

volumes:
  postgres_data:
  bundle_data:
